<?php
/**
 * BroadcastStatistics
 *
 * PHP version 5
 *
 * @category Class
 * @package  Thecodebunny\StreamingEngine
 * @author   TCB Codegen team
 * @link     https://github.com/tcb-api/tcb-codegen
 */

/**
 * Streaming Server REST API Reference
 *
 * Streaming Server REST API Reference
 *
 * OpenAPI spec version: V2.0
 * Contact: contact@thecodebunny.com
 * Generated by: https://github.com/tcb-api/tcb-codegen.git
 * TCB Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the tcb code generator program.
 * https://github.com/tcb-api/tcb-codegen
 * Do not edit the class manually.
 */

namespace Thecodebunny\StreamingEngine\Model;

use \ArrayAccess;
use \Thecodebunny\StreamingEngine\ObjectSerializer;

/**
 * BroadcastStatistics Class Doc Comment
 *
 * @category Class
 * @description The statistics class of the broadcasts
 * @package  Thecodebunny\StreamingEngine
 * @author   TCB Codegen team
 * @link     https://github.com/tcb-api/tcb-codegen
 */
class BroadcastStatistics implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $tcbModelName = 'BroadcastStatistics';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $tcbTypes = [
        'total_rtmp_watchers_count' => 'int',
        'total_hls_watchers_count' => 'int',
        'total_web_rtc_watchers_count' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $tcbFormats = [
        'total_rtmp_watchers_count' => 'int32',
        'total_hls_watchers_count' => 'int32',
        'total_web_rtc_watchers_count' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function tcbTypes()
    {
        return self::$tcbTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function tcbFormats()
    {
        return self::$tcbFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'total_rtmp_watchers_count' => 'totalRTMPWatchersCount',
        'total_hls_watchers_count' => 'totalHLSWatchersCount',
        'total_web_rtc_watchers_count' => 'totalWebRTCWatchersCount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'total_rtmp_watchers_count' => 'setTotalRtmpWatchersCount',
        'total_hls_watchers_count' => 'setTotalHlsWatchersCount',
        'total_web_rtc_watchers_count' => 'setTotalWebRtcWatchersCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'total_rtmp_watchers_count' => 'getTotalRtmpWatchersCount',
        'total_hls_watchers_count' => 'getTotalHlsWatchersCount',
        'total_web_rtc_watchers_count' => 'getTotalWebRtcWatchersCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$tcbModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['total_rtmp_watchers_count'] = isset($data['total_rtmp_watchers_count']) ? $data['total_rtmp_watchers_count'] : null;
        $this->container['total_hls_watchers_count'] = isset($data['total_hls_watchers_count']) ? $data['total_hls_watchers_count'] : null;
        $this->container['total_web_rtc_watchers_count'] = isset($data['total_web_rtc_watchers_count']) ? $data['total_web_rtc_watchers_count'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets total_rtmp_watchers_count
     *
     * @return int
     */
    public function getTotalRtmpWatchersCount()
    {
        return $this->container['total_rtmp_watchers_count'];
    }

    /**
     * Sets total_rtmp_watchers_count
     *
     * @param int $total_rtmp_watchers_count the total RTMP viewers of the stream
     *
     * @return $this
     */
    public function setTotalRtmpWatchersCount($total_rtmp_watchers_count)
    {
        $this->container['total_rtmp_watchers_count'] = $total_rtmp_watchers_count;

        return $this;
    }

    /**
     * Gets total_hls_watchers_count
     *
     * @return int
     */
    public function getTotalHlsWatchersCount()
    {
        return $this->container['total_hls_watchers_count'];
    }

    /**
     * Sets total_hls_watchers_count
     *
     * @param int $total_hls_watchers_count the total HLS viewers of the stream
     *
     * @return $this
     */
    public function setTotalHlsWatchersCount($total_hls_watchers_count)
    {
        $this->container['total_hls_watchers_count'] = $total_hls_watchers_count;

        return $this;
    }

    /**
     * Gets total_web_rtc_watchers_count
     *
     * @return int
     */
    public function getTotalWebRtcWatchersCount()
    {
        return $this->container['total_web_rtc_watchers_count'];
    }

    /**
     * Sets total_web_rtc_watchers_count
     *
     * @param int $total_web_rtc_watchers_count the total WebRTC viewers of the stream
     *
     * @return $this
     */
    public function setTotalWebRtcWatchersCount($total_web_rtc_watchers_count)
    {
        $this->container['total_web_rtc_watchers_count'] = $total_web_rtc_watchers_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


